# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - release/*

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"
  GitVersion.NuGetVersion: ""

steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: "5.x"

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      projects: "**/SimpleDatastore.csproj"
      arguments: "--configuration $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersion)"

  - task: DotNetCoreCLI@2
    displayName: "dotnet tests"
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: "pack"
      packagesToPack: "**/SimpleDatastore.csproj"
      nobuild: true
      packDirectory: "$(Build.ArtifactStagingDirectory)"
      versioningScheme: byEnvVar
      versionEnvVar: "GitVersion.NuGetVersion"

  - task: NuGetCommand@2
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "external"
      publishFeedCredentials: "nuget_robertgegorywest"
      versioningScheme: byEnvVar@2
      ersionEnvVar: "GitVersion.SemVer"
